# Generated by Django 3.2.25 on 2025-03-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250328_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='tokenExpiredTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
